name: Build Vue
on:
  push:
    branches:
      - master
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: Install npm
        run: npm install
      - name: Build app
        run: npm run build
      - name: GitHub Pages
        uses: ghaction-github-pages@v2.0.1
        with:
            target_branch: gh-pages
            build_dir: dist
            committer: Deploy
            username: 'leonorine'
            reponame: 'portefolio'
            token: ${{ secrets.TOKEN }}